name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-curl-winssl
            mingw-w64-i686-curl-winssl
      - name: Export MSYS2_ROOT
        run: echo "MSYS2_ROOT=$(msys2 -c 'cygpath -m /')" >> $env:GITHUB_ENV

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: hello-curl
          path: build/bin/
